from .button import Button
from .switch import Switch
from .door import Door
from .goal import Goal
from .hazard import Hazard
from .spring import Spring
from .key import Key
from .decoration import Decoration
from .platform import MovingPlatform
